# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_actualizarproducto.ui'
#
# Created: Wed Jul 13 19:10:34 2016
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_form_actualizarproducto(object):
    def setupUi(self, form_actualizarproducto):
        form_actualizarproducto.setObjectName("form_actualizarproducto")
        form_actualizarproducto.resize(990, 499)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 185, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 220, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 92, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 123, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 185, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 220, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 185, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 220, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 92, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 123, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 185, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 220, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 92, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 185, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 220, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 92, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 123, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 92, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 92, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 185, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 185, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 185, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        form_actualizarproducto.setPalette(palette)
        self.groupBox = QtWidgets.QGroupBox(form_actualizarproducto)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 951, 461))
        self.groupBox.setStyleSheet("background-color: rgb(211, 211, 255);")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 30, 931, 101))
        self.groupBox_2.setStyleSheet("QGroupBox{\n"
"background-color: rgb(225, 226, 255);\n"
"}\n"
"\n"
"QLabel{\n"
"background-color: rgb(225, 226, 255);\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 40, 59, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(290, 40, 59, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(588, 40, 71, 16))
        self.label_3.setObjectName("label_3")
        self.lne_nombre_filtro = QtWidgets.QLineEdit(self.groupBox_2)
        self.lne_nombre_filtro.setGeometry(QtCore.QRect(70, 39, 211, 21))
        self.lne_nombre_filtro.setObjectName("lne_nombre_filtro")
        self.lne_categoria = QtWidgets.QLineEdit(self.groupBox_2)
        self.lne_categoria.setGeometry(QtCore.QRect(663, 38, 231, 21))
        self.lne_categoria.setObjectName("lne_categoria")
        self.lne_tipo = QtWidgets.QLineEdit(self.groupBox_2)
        self.lne_tipo.setGeometry(QtCore.QRect(326, 38, 242, 21))
        self.lne_tipo.setObjectName("lne_tipo")
        self.boton_buscar = QtWidgets.QPushButton(self.groupBox_2)
        self.boton_buscar.setGeometry(QtCore.QRect(820, 70, 80, 20))
        self.boton_buscar.setObjectName("boton_buscar")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 150, 931, 271))
        self.groupBox_3.setStyleSheet("background-color: rgb(222, 223, 252);\n"
"background-color: rgb(225, 226, 255);")
        self.groupBox_3.setObjectName("groupBox_3")
        self.boton_actualizar = QtWidgets.QPushButton(self.groupBox)
        self.boton_actualizar.setGeometry(QtCore.QRect(860, 430, 80, 20))
        self.boton_actualizar.setObjectName("boton_actualizar")
        self.ckbx_vendible = QtWidgets.QCheckBox(form_actualizarproducto)
        self.ckbx_vendible.setGeometry(QtCore.QRect(81, 368, 111, 20))
        self.ckbx_vendible.setObjectName("ckbx_vendible")
        self.ckbx_activo = QtWidgets.QCheckBox(form_actualizarproducto)
        self.ckbx_activo.setGeometry(QtCore.QRect(790, 210, 111, 21))
        self.ckbx_activo.setObjectName("ckbx_activo")
        self.ckbx_consumible = QtWidgets.QCheckBox(form_actualizarproducto)
        self.ckbx_consumible.setGeometry(QtCore.QRect(525, 255, 111, 20))
        self.ckbx_consumible.setObjectName("ckbx_consumible")
        self.label_5 = QtWidgets.QLabel(form_actualizarproducto)
        self.label_5.setGeometry(QtCore.QRect(82, 302, 96, 16))
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(form_actualizarproducto)
        self.label_4.setGeometry(QtCore.QRect(84, 212, 56, 23))
        self.label_4.setObjectName("label_4")
        self.cbx_categoria = QtWidgets.QComboBox(form_actualizarproducto)
        self.cbx_categoria.setGeometry(QtCore.QRect(190, 273, 221, 20))
        self.cbx_categoria.setObjectName("cbx_categoria")
        self.label_6 = QtWidgets.QLabel(form_actualizarproducto)
        self.label_6.setGeometry(QtCore.QRect(82, 330, 102, 16))
        self.label_6.setObjectName("label_6")
        self.lne_precio_lista = QtWidgets.QLineEdit(form_actualizarproducto)
        self.lne_precio_lista.setGeometry(QtCore.QRect(190, 303, 281, 20))
        self.lne_precio_lista.setStyleSheet("QLineEdit{\n"
"background_color: white;\n"
"}")
        self.lne_precio_lista.setObjectName("lne_precio_lista")
        self.label_7 = QtWidgets.QLabel(form_actualizarproducto)
        self.label_7.setGeometry(QtCore.QRect(82, 273, 71, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(form_actualizarproducto)
        self.label_8.setGeometry(QtCore.QRect(519, 302, 121, 16))
        self.label_8.setStyleSheet("QCheckBox{\n"
"background-color: rgb(250, 217, 206);\n"
"}\n"
"")
        self.label_8.setObjectName("label_8")
        self.lne_precio_costo = QtWidgets.QLineEdit(form_actualizarproducto)
        self.lne_precio_costo.setGeometry(QtCore.QRect(190, 333, 281, 20))
        self.lne_precio_costo.setStyleSheet("QLineEdit{\n"
"background_color: white;\n"
"}")
        self.lne_precio_costo.setObjectName("lne_precio_costo")
        self.label_9 = QtWidgets.QLabel(form_actualizarproducto)
        self.label_9.setGeometry(QtCore.QRect(82, 244, 34, 16))
        self.label_9.setObjectName("label_9")
        self.ckbx_comprable = QtWidgets.QCheckBox(form_actualizarproducto)
        self.ckbx_comprable.setGeometry(QtCore.QRect(81, 395, 111, 20))
        self.ckbx_comprable.setObjectName("ckbx_comprable")
        self.cbx_unidad_medida = QtWidgets.QComboBox(form_actualizarproducto)
        self.cbx_unidad_medida.setGeometry(QtCore.QRect(650, 300, 121, 20))
        self.cbx_unidad_medida.setObjectName("cbx_unidad_medida")
        self.lne_nombre_resultado = QtWidgets.QLineEdit(form_actualizarproducto)
        self.lne_nombre_resultado.setGeometry(QtCore.QRect(190, 213, 581, 20))
        self.lne_nombre_resultado.setObjectName("lne_nombre_resultado")
        self.cbx_tipo = QtWidgets.QComboBox(form_actualizarproducto)
        self.cbx_tipo.setGeometry(QtCore.QRect(190, 243, 221, 20))
        self.cbx_tipo.setObjectName("cbx_tipo")
        self.label_4.setBuddy(self.lne_nombre_filtro)

        self.retranslateUi(form_actualizarproducto)
        QtCore.QMetaObject.connectSlotsByName(form_actualizarproducto)

    def retranslateUi(self, form_actualizarproducto):
        _translate = QtCore.QCoreApplication.translate
        form_actualizarproducto.setWindowTitle(_translate("form_actualizarproducto", "Actualizar Producto"))
        self.groupBox.setTitle(_translate("form_actualizarproducto", "Actualizar Producto"))
        self.groupBox_2.setTitle(_translate("form_actualizarproducto", "Filtro de Búsqueda"))
        self.label.setText(_translate("form_actualizarproducto", "Nombre :"))
        self.label_2.setText(_translate("form_actualizarproducto", "Tipo:"))
        self.label_3.setText(_translate("form_actualizarproducto", "Categoría: "))
        self.boton_buscar.setText(_translate("form_actualizarproducto", "Buscar"))
        self.groupBox_3.setTitle(_translate("form_actualizarproducto", "Resultados de Búsqueda"))
        self.boton_actualizar.setText(_translate("form_actualizarproducto", "Actualizar"))
        self.ckbx_vendible.setText(_translate("form_actualizarproducto", "Vendible"))
        self.ckbx_activo.setText(_translate("form_actualizarproducto", "Activo"))
        self.ckbx_consumible.setText(_translate("form_actualizarproducto", "Consumible"))
        self.label_5.setText(_translate("form_actualizarproducto", "Precio de Lista :"))
        self.label_4.setText(_translate("form_actualizarproducto", "Nombre :"))
        self.label_6.setText(_translate("form_actualizarproducto", "Precio de Costo :"))
        self.label_7.setText(_translate("form_actualizarproducto", "Categoria :"))
        self.label_8.setText(_translate("form_actualizarproducto", "Unidad de Medida :"))
        self.label_9.setText(_translate("form_actualizarproducto", "Tipo :"))
        self.ckbx_comprable.setText(_translate("form_actualizarproducto", "Comprable"))

