# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_buscarprofesionales.ui'
#
# Created: Wed Jul 13 18:59:42 2016
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_form_buscaprofesionales(object):
    def setupUi(self, form_buscaprofesionales):
        form_buscaprofesionales.setObjectName("form_buscaprofesionales")
        form_buscaprofesionales.resize(878, 572)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(89, 108, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(219, 242, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(92, 115, 121))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 153, 162))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(89, 108, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(89, 108, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(219, 242, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(89, 108, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(219, 242, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(92, 115, 121))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 153, 162))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(89, 108, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(89, 108, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(219, 242, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(92, 115, 121))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(89, 108, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(219, 242, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(92, 115, 121))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 153, 162))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(92, 115, 121))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(92, 115, 121))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(89, 108, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(89, 108, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 230, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        form_buscaprofesionales.setPalette(palette)
        form_buscaprofesionales.setStyleSheet("background-color: rgb(89, 108, 112);")
        self.tabWidget = QtWidgets.QTabWidget(form_buscaprofesionales)
        self.tabWidget.setGeometry(QtCore.QRect(16, 20, 841, 531))
        self.tabWidget.setStyleSheet("background-color: rgb(110, 138, 145);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(30, 10, 781, 461))
        self.groupBox.setStyleSheet("background-color: rgb(151, 190, 200);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 180, 761, 21))
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 50, 151, 20))
        self.label.setObjectName("label")
        self.lne_apellidoynombre = QtWidgets.QLineEdit(self.groupBox)
        self.lne_apellidoynombre.setGeometry(QtCore.QRect(150, 47, 191, 20))
        self.lne_apellidoynombre.setStyleSheet("QGroupBox{\n"
"border-width: 2px;\n"
"border-style: solid;\n"
"border-color:rgb(210, 255, 252);\n"
"}\n"
"QGroupBox#groupBox{\n"
"background-color: rgb(229, 228, 203);\n"
"}\n"
"QLineEdit{\n"
"background-color: white;\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-color: grey;\n"
"}")
        self.lne_apellidoynombre.setObjectName("lne_apellidoynombre")
        self.cbx_localidad = QtWidgets.QComboBox(self.groupBox)
        self.cbx_localidad.setGeometry(QtCore.QRect(470, 107, 181, 20))
        self.cbx_localidad.setAutoFillBackground(False)
        self.cbx_localidad.setObjectName("cbx_localidad")
        self.cbx_localidad.addItem("")
        self.cbx_localidad.setItemText(0, "")
        self.cbx_localidad.addItem("")
        self.cbx_localidad.addItem("")
        self.cbx_localidad.addItem("")
        self.cbx_localidad.addItem("")
        self.cbx_localidad.addItem("")
        self.cbx_localidad.addItem("")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(34, 108, 151, 20))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(34, 78, 151, 20))
        self.label_2.setObjectName("label_2")
        self.lne_doc = QtWidgets.QLineEdit(self.groupBox)
        self.lne_doc.setGeometry(QtCore.QRect(150, 77, 191, 20))
        self.lne_doc.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_doc.setObjectName("lne_doc")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(350, 77, 101, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(350, 107, 101, 20))
        self.label_6.setObjectName("label_6")
        self.lne_nrolegajo = QtWidgets.QLineEdit(self.groupBox)
        self.lne_nrolegajo.setGeometry(QtCore.QRect(150, 107, 191, 20))
        self.lne_nrolegajo.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
" border-color: grey;\n"
"}")
        self.lne_nrolegajo.setObjectName("lne_nrolegajo")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(350, 47, 101, 20))
        self.label_4.setStyleSheet("QLabel{\n"
"font: 9pt \"Sans Serif\";\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.label_4.setObjectName("label_4")
        self.boton_buscar = QtWidgets.QPushButton(self.groupBox)
        self.boton_buscar.setGeometry(QtCore.QRect(650, 140, 80, 23))
        self.boton_buscar.setObjectName("boton_buscar")
        self.boton_limpiarn_2 = QtWidgets.QPushButton(self.groupBox)
        self.boton_limpiarn_2.setGeometry(QtCore.QRect(550, 140, 80, 23))
        self.boton_limpiarn_2.setObjectName("boton_limpiarn_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(13, 7, 761, 21))
        self.groupBox_3.setStyleSheet("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setGeometry(QtCore.QRect(10, 220, 761, 221))
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setStyleSheet("background-color: rgb(189, 237, 246);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setItem(0, 0, item)
        self.cbx_obrasocial = QtWidgets.QComboBox(self.groupBox)
        self.cbx_obrasocial.setGeometry(QtCore.QRect(470, 80, 181, 20))
        self.cbx_obrasocial.setAutoFillBackground(False)
        self.cbx_obrasocial.setObjectName("cbx_obrasocial")
        self.cbx_obrasocial.addItem("")
        self.cbx_obrasocial.setItemText(0, "")
        self.cbx_obrasocial.addItem("")
        self.cbx_obrasocial.addItem("")
        self.cbx_obrasocial.addItem("")
        self.cbx_obrasocial.addItem("")
        self.cbx_obrasocial.addItem("")
        self.cbx_obrasocial.addItem("")
        self.cbx_especialidad = QtWidgets.QComboBox(self.groupBox)
        self.cbx_especialidad.setGeometry(QtCore.QRect(470, 50, 181, 20))
        self.cbx_especialidad.setAutoFillBackground(False)
        self.cbx_especialidad.setObjectName("cbx_especialidad")
        self.cbx_especialidad.addItem("")
        self.cbx_especialidad.setItemText(0, "")
        self.cbx_especialidad.addItem("")
        self.cbx_especialidad.addItem("")
        self.cbx_especialidad.addItem("")
        self.cbx_especialidad.addItem("")
        self.cbx_especialidad.addItem("")
        self.cbx_especialidad.addItem("")
        self.tabWidget.addTab(self.tab_3, "")
        self.label.setBuddy(self.lne_apellidoynombre)
        self.label_3.setBuddy(self.lne_nrolegajo)
        self.label_2.setBuddy(self.lne_doc)
        self.label_6.setBuddy(self.cbx_localidad)

        self.retranslateUi(form_buscaprofesionales)
        self.tabWidget.setCurrentIndex(0)
        self.boton_limpiarn_2.clicked.connect(self.lne_apellidoynombre.clear)
        self.boton_limpiarn_2.clicked.connect(self.lne_doc.clear)
        self.boton_limpiarn_2.clicked.connect(self.cbx_localidad.clear)
        self.boton_limpiarn_2.clicked.connect(self.lne_nrolegajo.clear)
        QtCore.QMetaObject.connectSlotsByName(form_buscaprofesionales)
        form_buscaprofesionales.setTabOrder(self.tabWidget, self.lne_apellidoynombre)
        form_buscaprofesionales.setTabOrder(self.lne_apellidoynombre, self.lne_doc)
        form_buscaprofesionales.setTabOrder(self.lne_doc, self.lne_nrolegajo)
        form_buscaprofesionales.setTabOrder(self.lne_nrolegajo, self.cbx_localidad)
        form_buscaprofesionales.setTabOrder(self.cbx_localidad, self.boton_limpiarn_2)
        form_buscaprofesionales.setTabOrder(self.boton_limpiarn_2, self.boton_buscar)
        form_buscaprofesionales.setTabOrder(self.boton_buscar, self.tableWidget)

    def retranslateUi(self, form_buscaprofesionales):
        _translate = QtCore.QCoreApplication.translate
        form_buscaprofesionales.setWindowTitle(_translate("form_buscaprofesionales", "Buscar Profesionales"))
        self.groupBox_2.setTitle(_translate("form_buscaprofesionales", "Grilla de Resultados"))
        self.label.setText(_translate("form_buscaprofesionales", "Apellido y Nombre:"))
        self.cbx_localidad.setItemText(1, _translate("form_buscaprofesionales", "Viedma"))
        self.cbx_localidad.setItemText(2, _translate("form_buscaprofesionales", "New Item"))
        self.cbx_localidad.setItemText(3, _translate("form_buscaprofesionales", "New Item"))
        self.cbx_localidad.setItemText(4, _translate("form_buscaprofesionales", "New Item"))
        self.cbx_localidad.setItemText(5, _translate("form_buscaprofesionales", "New Item"))
        self.cbx_localidad.setItemText(6, _translate("form_buscaprofesionales", "New Item"))
        self.label_3.setText(_translate("form_buscaprofesionales", "Nro. Legajo:"))
        self.label_2.setText(_translate("form_buscaprofesionales", "Nro.Documento:"))
        self.label_5.setText(_translate("form_buscaprofesionales", "Obra Social"))
        self.label_6.setText(_translate("form_buscaprofesionales", "Localidad:"))
        self.label_4.setText(_translate("form_buscaprofesionales", "Especialidad:"))
        self.boton_buscar.setText(_translate("form_buscaprofesionales", "Buscar"))
        self.boton_limpiarn_2.setText(_translate("form_buscaprofesionales", "Limpiar"))
        self.groupBox_3.setTitle(_translate("form_buscaprofesionales", "Filtros de Búsqueda"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("form_buscaprofesionales", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("form_buscaprofesionales", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("form_buscaprofesionales", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("form_buscaprofesionales", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("form_buscaprofesionales", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("form_buscaprofesionales", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("form_buscaprofesionales", "7"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("form_buscaprofesionales", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("form_buscaprofesionales", "Apellido y Nombre"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("form_buscaprofesionales", "Nro. Legajo"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("form_buscaprofesionales", "Especialidad"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("form_buscaprofesionales", "Domicilio"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("form_buscaprofesionales", "Localidad"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("form_buscaprofesionales", "CUIT/CUIL"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("form_buscaprofesionales", "Obra Social"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.cbx_obrasocial.setItemText(1, _translate("form_buscaprofesionales", "Viedma"))
        self.cbx_obrasocial.setItemText(2, _translate("form_buscaprofesionales", "New Item"))
        self.cbx_obrasocial.setItemText(3, _translate("form_buscaprofesionales", "New Item"))
        self.cbx_obrasocial.setItemText(4, _translate("form_buscaprofesionales", "New Item"))
        self.cbx_obrasocial.setItemText(5, _translate("form_buscaprofesionales", "New Item"))
        self.cbx_obrasocial.setItemText(6, _translate("form_buscaprofesionales", "New Item"))
        self.cbx_especialidad.setItemText(1, _translate("form_buscaprofesionales", "Viedma"))
        self.cbx_especialidad.setItemText(2, _translate("form_buscaprofesionales", "New Item"))
        self.cbx_especialidad.setItemText(3, _translate("form_buscaprofesionales", "New Item"))
        self.cbx_especialidad.setItemText(4, _translate("form_buscaprofesionales", "New Item"))
        self.cbx_especialidad.setItemText(5, _translate("form_buscaprofesionales", "New Item"))
        self.cbx_especialidad.setItemText(6, _translate("form_buscaprofesionales", "New Item"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("form_buscaprofesionales", "Búsqueda de Profesionales"))

