# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Thu Jul 14 10:06:30 2016
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_form_MainWindow(object):
    def setupUi(self, form_MainWindow):
        form_MainWindow.setObjectName("form_MainWindow")
        form_MainWindow.setWindowModality(QtCore.Qt.NonModal)
        form_MainWindow.resize(998, 554)
        self.centralWidget = QtWidgets.QWidget(form_MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        form_MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(form_MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 998, 20))
        self.menuBar.setObjectName("menuBar")
        self.menuProfesionales = QtWidgets.QMenu(self.menuBar)
        self.menuProfesionales.setObjectName("menuProfesionales")
        self.menuServicios = QtWidgets.QMenu(self.menuBar)
        self.menuServicios.setObjectName("menuServicios")
        self.menuConfiguracion = QtWidgets.QMenu(self.menuServicios)
        self.menuConfiguracion.setObjectName("menuConfiguracion")
        self.menuUsaurios = QtWidgets.QMenu(self.menuBar)
        self.menuUsaurios.setObjectName("menuUsaurios")
        self.menuProductos = QtWidgets.QMenu(self.menuBar)
        self.menuProductos.setObjectName("menuProductos")
        self.menuFacturacion = QtWidgets.QMenu(self.menuBar)
        self.menuFacturacion.setObjectName("menuFacturacion")
        form_MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(form_MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        form_MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(form_MainWindow)
        self.statusBar.setObjectName("statusBar")
        form_MainWindow.setStatusBar(self.statusBar)
        self.actionAgregar_Profesional = QtWidgets.QAction(form_MainWindow)
        self.actionAgregar_Profesional.setObjectName("actionAgregar_Profesional")
        self.actionAcutalizar_profesional = QtWidgets.QAction(form_MainWindow)
        self.actionAcutalizar_profesional.setObjectName("actionAcutalizar_profesional")
        self.actionBorrar_Profesional = QtWidgets.QAction(form_MainWindow)
        self.actionBorrar_Profesional.setObjectName("actionBorrar_Profesional")
        self.actionBuscar_Profesional = QtWidgets.QAction(form_MainWindow)
        self.actionBuscar_Profesional.setObjectName("actionBuscar_Profesional")
        self.actionContratos = QtWidgets.QAction(form_MainWindow)
        self.actionContratos.setObjectName("actionContratos")
        self.actionNuevo_Contrato = QtWidgets.QAction(form_MainWindow)
        self.actionNuevo_Contrato.setObjectName("actionNuevo_Contrato")
        self.actionBuscar_Contrato = QtWidgets.QAction(form_MainWindow)
        self.actionBuscar_Contrato.setObjectName("actionBuscar_Contrato")
        self.actionNuevo_Usuario = QtWidgets.QAction(form_MainWindow)
        self.actionNuevo_Usuario.setObjectName("actionNuevo_Usuario")
        self.actionServicios_de_contratos = QtWidgets.QAction(form_MainWindow)
        self.actionServicios_de_contratos.setObjectName("actionServicios_de_contratos")
        self.actionBuscar_Productos = QtWidgets.QAction(form_MainWindow)
        self.actionBuscar_Productos.setObjectName("actionBuscar_Productos")
        self.actionNuevo_Producto = QtWidgets.QAction(form_MainWindow)
        self.actionNuevo_Producto.setObjectName("actionNuevo_Producto")
        self.actionBorrar_Producto = QtWidgets.QAction(form_MainWindow)
        self.actionBorrar_Producto.setObjectName("actionBorrar_Producto")
        self.actionActualizar_Productos = QtWidgets.QAction(form_MainWindow)
        self.actionActualizar_Productos.setObjectName("actionActualizar_Productos")
        self.actionNueva_Factura = QtWidgets.QAction(form_MainWindow)
        self.actionNueva_Factura.setObjectName("actionNueva_Factura")
        self.actionBuscar_Factura = QtWidgets.QAction(form_MainWindow)
        self.actionBuscar_Factura.setObjectName("actionBuscar_Factura")
        self.actionActualizar_Factura = QtWidgets.QAction(form_MainWindow)
        self.actionActualizar_Factura.setObjectName("actionActualizar_Factura")
        self.actionBorrar_Factura = QtWidgets.QAction(form_MainWindow)
        self.actionBorrar_Factura.setObjectName("actionBorrar_Factura")
        self.actionGenerar_Facturas = QtWidgets.QAction(form_MainWindow)
        self.actionGenerar_Facturas.setObjectName("actionGenerar_Facturas")
        self.actionBorrar_Usuario = QtWidgets.QAction(form_MainWindow)
        self.actionBorrar_Usuario.setObjectName("actionBorrar_Usuario")
        self.actionGenerar_Consumo = QtWidgets.QAction(form_MainWindow)
        self.actionGenerar_Consumo.setObjectName("actionGenerar_Consumo")
        self.menuProfesionales.addAction(self.actionAgregar_Profesional)
        self.menuProfesionales.addAction(self.actionAcutalizar_profesional)
        self.menuProfesionales.addAction(self.actionBorrar_Profesional)
        self.menuProfesionales.addAction(self.actionBuscar_Profesional)
        self.menuConfiguracion.addAction(self.actionServicios_de_contratos)
        self.menuServicios.addAction(self.actionNuevo_Contrato)
        self.menuServicios.addAction(self.actionBuscar_Contrato)
        self.menuServicios.addAction(self.actionGenerar_Facturas)
        self.menuServicios.addAction(self.actionGenerar_Consumo)
        self.menuServicios.addAction(self.menuConfiguracion.menuAction())
        self.menuUsaurios.addAction(self.actionNuevo_Usuario)
        self.menuUsaurios.addAction(self.actionBorrar_Usuario)
        self.menuProductos.addAction(self.actionBuscar_Productos)
        self.menuProductos.addAction(self.actionNuevo_Producto)
        self.menuProductos.addAction(self.actionBorrar_Producto)
        self.menuProductos.addAction(self.actionActualizar_Productos)
        self.menuFacturacion.addAction(self.actionNueva_Factura)
        self.menuFacturacion.addAction(self.actionBuscar_Factura)
        self.menuFacturacion.addAction(self.actionActualizar_Factura)
        self.menuFacturacion.addAction(self.actionBorrar_Factura)
        self.menuBar.addAction(self.menuProfesionales.menuAction())
        self.menuBar.addAction(self.menuProductos.menuAction())
        self.menuBar.addAction(self.menuServicios.menuAction())
        self.menuBar.addAction(self.menuFacturacion.menuAction())
        self.menuBar.addAction(self.menuUsaurios.menuAction())

        self.retranslateUi(form_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(form_MainWindow)

    def retranslateUi(self, form_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        form_MainWindow.setWindowTitle(_translate("form_MainWindow", "MainWindow"))
        self.menuProfesionales.setTitle(_translate("form_MainWindow", "Profesionales"))
        self.menuServicios.setTitle(_translate("form_MainWindow", "Contratos"))
        self.menuConfiguracion.setTitle(_translate("form_MainWindow", "Configuración"))
        self.menuUsaurios.setTitle(_translate("form_MainWindow", "Usuarios"))
        self.menuProductos.setTitle(_translate("form_MainWindow", "Productos"))
        self.menuFacturacion.setTitle(_translate("form_MainWindow", "Facturación"))
        self.actionAgregar_Profesional.setText(_translate("form_MainWindow", "Agregar Profesional"))
        self.actionAcutalizar_profesional.setText(_translate("form_MainWindow", "Acutalizar Profesional"))
        self.actionBorrar_Profesional.setText(_translate("form_MainWindow", "Borrar Profesional"))
        self.actionBuscar_Profesional.setText(_translate("form_MainWindow", "Buscar Profesional"))
        self.actionContratos.setText(_translate("form_MainWindow", "contratos"))
        self.actionNuevo_Contrato.setText(_translate("form_MainWindow", "Nuevo Contratos"))
        self.actionBuscar_Contrato.setText(_translate("form_MainWindow", "Buscar Contratos"))
        self.actionNuevo_Usuario.setText(_translate("form_MainWindow", "Nuevo Usuario"))
        self.actionServicios_de_contratos.setText(_translate("form_MainWindow", "Servicios de contratos"))
        self.actionBuscar_Productos.setText(_translate("form_MainWindow", "Buscar Productos"))
        self.actionNuevo_Producto.setText(_translate("form_MainWindow", "Nuevo Producto"))
        self.actionBorrar_Producto.setText(_translate("form_MainWindow", "Borrar Producto"))
        self.actionActualizar_Productos.setText(_translate("form_MainWindow", "Actualizar Producto"))
        self.actionNueva_Factura.setText(_translate("form_MainWindow", "Nueva Factura"))
        self.actionBuscar_Factura.setText(_translate("form_MainWindow", "Buscar Factura"))
        self.actionActualizar_Factura.setText(_translate("form_MainWindow", "Actualizar Factura"))
        self.actionBorrar_Factura.setText(_translate("form_MainWindow", "Borrar Factura"))
        self.actionGenerar_Facturas.setText(_translate("form_MainWindow", "Generar Facturas"))
        self.actionBorrar_Usuario.setText(_translate("form_MainWindow", "Borrar Usuario"))
        self.actionGenerar_Consumo.setText(_translate("form_MainWindow", "Generar Consumo"))

